apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creative-app
  template:
    metadata:
      labels:
        app: creative-app
    spec:
      containers:
      - name: creative-container
        image: aks-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
